#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────
# scripts/setup.sh — Initialisation idempotente du projet
# ──────────────────────────────────────────────────────────────────────
# Idempotence : peut être lancé indéfiniment sans effet secondaire
# Déterministe : même état initial → même résultat
# ──────────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "🔧 Initialisation de ${PROJECT_ROOT##*/}..."

# ── 1. Git ─────────────────────────────────────────────────────────
if [ -d "$PROJECT_ROOT/.git" ]; then
    echo "✅ Git déjà initialisé"
else
    echo "📦 Initialisation Git..."
    git -C "$PROJECT_ROOT" init
    git -C "$PROJECT_ROOT" add .
    git -C "$PROJECT_ROOT" commit -m "chore: initial scaffold" --no-verify
    echo "✅ Git initialisé"
fi

# ── 2. Branches par défaut ─────────────────────────────────────────
CURRENT_BRANCH=$(git -C "$PROJECT_ROOT" branch --show-current 2>/dev/null || true)
if [ "$CURRENT_BRANCH" = "main" ] || [ "$CURRENT_BRANCH" = "master" ]; then
    echo "✅ Branche principale configurée"
else
    echo "🌿 Création de la branche principale..."
    git -C "$PROJECT_ROOT" checkout -b main 2>/dev/null || true
    echo "✅ Branche principale configurée"
fi

# ── 3. Structure des fichiers ──────────────────────────────────────
ensure_file() {
    local filepath="$PROJECT_ROOT/$1"
    if [ -f "$filepath" ]; then
        return 0
    fi
    
    local default_content="$2"
    mkdir -p "$(dirname "$filepath")"
    printf '%s' "$default_content" > "$filepath"
    git -C "$PROJECT_ROOT" add "$1" 2>/dev/null || true
    echo "  ✏️  Créé : $1"
}

ensure_file "VERSION" "0.0.0\n"
ensure_file "LICENSE" "MIT License\n"
ensure_file "README.md" "# ${PROJECT_ROOT##*/}\n\n> Project description\n"
ensure_file "CHANGELOG.md" "## [Unreleased]\n\n### Added\n- Initial scaffold\n"
ensure_file ".gitignore" "# Generated by setup\n"
ensure_file "src/.gitkeep" ""
ensure_file "tests/.gitkeep" ""

# ── 4. Commit des éventuelles corrections ──────────────────────────
cd "$PROJECT_ROOT"
git add -A
if git diff --cached --quiet 2>/dev/null; then
    echo "✅ Projet correctement initialisé"
else
    git commit -m "chore: final scaffold commit" --no-verify
    echo "✅ Scaffold initial"
fi

echo ""
echo "🎉 Initialisation terminée !"
